# --------------------------------------------------------------------------
# Status line customisation
# --------------------------------------------------------------------------
set -g mode-style "fg=#93A1A1,bg=#383A3E"

set -g message-style "fg=#93A1A1,bg=default"
set -g message-command-style "fg=#93A1A1,bg=default"

set -g pane-border-style "fg=#93A1A1"
set -g pane-active-border-style "fg=#93A1A1"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#93A1A1,bg=default"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#93A1A1,bold][ #(echo #{session_name} | tr '[:lower:]' '[:upper:]') ] "
set -g status-right "#[fg=#93A1A1,bold][ #{p:pane_current_command} | #h ]"

setw -g window-status-activity-style "underscore,fg=#15161E,bg=#75888A"
setw -g window-status-separator " "
setw -g window-status-style "NONE,fg=#93A1A1"
setw -g window-status-format '#[default]#I: #[default]#{b:pane_current_path}#{?window_zoomed_flag, ⛶}'
setw -g window-status-current-format '#[fg=#eee3d5,bg=default,bold]{ #I: #{b:pane_current_path}#{?window_zoomed_flag, ⛶} }'

