# --------------------------------------------------------------------------
# Status line customisation
# --------------------------------------------------------------------------
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100
set -gw automatic-rename on
set -gw automatic-rename-format '#{b:pane_current_path}'
set -g set-titles on
set -g set-titles-string '#h:#W'

# Theme
set -g status-style "bg=default,fg=default"
set -g status-left "#[fg=#1E2128,bg=default]#[bg=#1E2128,fg=#ABB2BF,bold] #(echo #{session_name} | tr '[:lower:]' '[:upper:]') #[fg=#1E2128,bg=#647373]#[fg=#647373,bg=#485252]#[fg=#485252,bg=default] "
set -g status-right "#[fg=#93A1A1]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#[fg=#93A1A1]#{p:pane_current_command} ❘ #h "
setw -g window-status-format '#[fg=brightblack]#I:#{b:pane_current_path}#{?window_zoomed_flag,ʺ}'
setw -g window-status-current-format '#[fg=#93A1A1,bg=default,bold]{ #I:#{b:pane_current_path}#{?window_zoomed_flag,ʺ} }'
set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=#93A1A1"
set -g message-style "bg=default,fg=#93A1A1"
set -g message-command-style "bg=default,fg=#93A1A1"
set -g mode-style "bg=#93A1A1,fg=black"
