# --------------------------------------------------------------------------
# Status line customisation
# --------------------------------------------------------------------------
set -g mode-style "fg=#eee8d5,bg=#748789"

set -g message-style "fg=#eee8d5,bg=default"
set -g message-command-style "fg=#eee8d5,bg=default"

set -g pane-border-style "fg=#748789"
set -g pane-active-border-style "fg=#eee8d5"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#586e75,bg=default"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#748789,bg=default]#[fg=#15161E,bg=#748789,bold] #S #[fg=#748789,bg=default] "
set -g status-right "#[fg=#586e75,bg=default,nobold,nounderscore,noitalics]#[fg=#93a1a1,bg=#586e75]#[fg=#657b83,bg=#586e75,nobold,nounderscore,noitalics]#[fg=#93a1a1,bg=#657b83]#[fg=#748789,bg=#657b83,nobold,nounderscore,noitalics]#[fg=#21252b,bg=#748789,bold] #h #[fg=#748789,bg=default]"
# set -g status-right "#[fg=#586e75,bg=default,nobold,nounderscore,noitalics]#[fg=#93a1a1,bg=#586e75]#[fg=#657b83,bg=#586e75,nobold,nounderscore,noitalics]#[fg=#93a1a1,bg=#657b83]#[fg=#383A3E,bg=#657b83,nobold,nounderscore,noitalics]#[fg=#93A1A1,bg=#383A3E,bold] #{pane_current_command} | #h#[fg=#383A3E,bg=default]"

setw -g window-status-activity-style "underscore,fg=#748789,bg=#002b36"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#748789"
setw -g window-status-format '#[default] #I  #{b:pane_current_path} #{?window_zoomed_flag,⛶}'
setw -g window-status-current-format '#[fg=#748789,bg=default]#[fg=#21252b,bg=#748789,bold] #I  #{b:pane_current_path} #{?window_zoomed_flag,⛶,} #[fg=#748789,bg=default]'
