return {
  {
    "catppuccin/nvim",
    lazy = true,
    name = "catppuccin",
    opts = {
      flavour = "mocha", -- latte, frappe, macchiato, mocha
      -- flavour = "frappe",
      -- transparent_background = true, -- disables setting the background color.
      integrations = {
        barbecue = { dim_dirname = true, bold_basename = true, dim_context = false, alt_background = false },
        cmp = true,
        gitsigns = true,
        hop = true,
        illuminate = { enabled = true },
        native_lsp = { enabled = true, inlay_hints = { background = true } },
        neogit = true,
        neotree = true,
        semantic_tokens = true,
        treesitter = true,
        treesitter_context = true,
        vimwiki = true,
        which_key = true,
        aerial = true,
        fidget = true,
        mason = true,
        neotest = true,
        dap_ui = true,
        telescope = {
          enabled = true,
          style = "nvchad",
        },
      },
      highlight_overrides = {
        -- all = function(colors)
        --   return {
        --     NeotestPassed = { fg = colors.green },
        --     NeotestFailed = { fg = colors.red },
        --     NeotestRunning = { fg = colors.yellow },
        --     NeotestSkipped = { fg = colors.blue },
        --     NeotestFile = { fg = colors.peach },
        --     NeotestNamespace = { fg = colors.peach },
        --     NeotestDir = { fg = colors.peach },
        --     NeotestFocused = { fg = colors.mauve, bold = true, underline = true },
        --     NeotestAdapterName = { fg = colors.red },
        --     NeotestIndent = { fg = colors.yellow },
        --     NeotestExpandMarker = { fg = colors.yellow },
        --     NeotestWinSelect = { fg = colors.yellow, bold = true },
        --     NeotestTest = { fg = colors.subtext2 },
        --     FzfLuaNormal = { bg = colors.base },
        --     FzfLuaBorder = { fg = colors.base, bg = colors.base },
        --     FzfluaTitle = { fg = colors.text, bg = colors.overlay0, style = { "bold" } },
        --     FzfLuaBackdrop = { bg = colors.surface0 },
        --     FzfLuaPreviewNormal = { bg = colors.surface0 },
        --     FzfLuaPreviewBorder = { fg = colors.surface0, bg = colors.surface0 },
        --     FzfLuaScrollBorderEmpty = { fg = colors.surface0, bg = colors.surface0 },
        --     FzfLuaScrollBorderFull = { fg = colors.subtext1, bg = colors.surface0 },
        --     FzfLuaScrollFloatEmpty = { fg = colors.surface0, bg = colors.surface0 },
        --     FzfLuaScrollFloatFull = { fg = colors.subtext1, bg = colors.surface0 },
        --     FzfLuaCursorLine = { bg = colors.surface2 },
        --     TelescopeBorder = { fg = colors.base, bg = colors.base },
        --     TelescopeNormal = { bg = colors.base },
        --     TelescopePreviewBorder = { fg = colors.surface0, bg = colors.surface0 },
        --     TelescopePreviewNormal = { bg = colors.surface0 },
        --     TelescopePreviewTitle = { fg = colors.text, bg = colors.overlay0, style = { "bold" } },
        --     TelescopePromptBorder = { fg = colors.base, bg = colors.base },
        --     TelescopePromptNormal = { fg = colors.text, bg = colors.base },
        --     TelescopePromptTitle = { fg = colors.text, bg = colors.overlay0, style = { "bold" } },
        --   }
        -- end,
      },
      color_overrides = {
        latte = {
          rosewater = "#DC8A78",
          flamingo = "#DD7878",
          mauve = "#CBA6F7",
          pink = "#F5C2E7",
          red = "#E95678",
          maroon = "#B33076",
          peach = "#FF8700",
          yellow = "#F7BB3B",
          green = "#AFD700",
          blue = "#61AFEF",
          sky = "#04A5E5",
          teal = "#B5E8E0",
          lavender = "#7287FD",

          text = "#F2F2BF",
          subtext1 = "#BAC2DE",
          subtext0 = "#A6ADC8",
          overlay2 = "#C3BAC6",
          overlay1 = "#988BA2",
          overlay0 = "#6E6B6B",
          surface2 = "#6E6C7E",
          surface1 = "#575268",
          surface0 = "#302D41",

          base = "#1D1536",
          mantle = "#1C1C19",
          crust = "#161320",
        },
        mocha = {
          rosewater = "#ea6962",
          flamingo = "#ea6962",
          red = "#ea6962",
          maroon = "#ea6962",
          pink = "#d3869b",
          mauve = "#d3869b",
          peach = "#e78a4e",
          yellow = "#d8a657",
          green = "#a9b665",
          teal = "#89b482",
          sky = "#89b482",
          sapphire = "#89b482",
          blue = "#7daea3",
          lavender = "#7daea3",
          text = "#ebdbb2",
          subtext1 = "#d5c4a1",
          subtext0 = "#bdae93",
          overlay2 = "#a89984",
          overlay1 = "#928374",
          overlay0 = "#595959",
          surface2 = "#4d4d4d",
          surface1 = "#737373",
          surface0 = "#292929",
          base = "#1d2021",
          mantle = "#191b1c",
          crust = "#141617",
        },
      },
    },
  },
  -- {
  --   "folke/tokyonight.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   opts = {
  --     style = "moon",
  --     transparent = true,
  --     styles = {
  --       comments = { italic = true },
  --       keywords = { italic = true },
  --       functions = {},
  --       variables = {},
  --       -- Background styles. Can be "dark", "transparent" or "normal"
  --       sidebars = "transparent", -- style for sidebars, see below
  --       floats = "transparent", -- style for floating windows
  --     },
  --   },
  -- },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "one_monokai",
    },
  },
  {
    "cpea2506/one_monokai.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      require("one_monokai").setup({
        transparent = true,
        highlights = function(colors)
          return {
            Normal = { bg = colors.none },
            NormalNC = { bg = colors.none },
            StatusLine = { bg = colors.none },
            StatusLineNC = { bg = colors.none },
          }
        end,
      })
      vim.cmd.colorscheme("one_monokai")
    end,
  },
}
